---
- name: check users password valid time
  shell: getent shadow "{{ users }}" | cut -d':' -f5
  register: users_pw_valid
  changed_when: False
 
- name: set users password valid time
  shell: chage -M "{{ user_password_valid_time }}" "{{ users }}"
  when: users_pw_valid.stdout is defined and users_pw_valid.stdout !=  user_password_valid_time
